### PR TITLE
Add Wheezy Web to benchmarked frameworks

### PR DESCRIPTION
**Pull request by leth**
I have to admit I've only tested the `/json` path, but The code looks fine, and it's mostly copied from elsewhere ;)

### CODE REVIEW

**Comment by leth** [comment]
Actually, there might be a better way to to templates, I'll see if I can work it out.

**Comment by leth** [comment]
I tried the approach of using the code in `BaseHandler` but it brought in too much extra stuff I didn't need.

**Comment by klen** [comment]
Thank you!

**Comment by leth** [comment]
Do let me know when you get a chance to re-do the results :-)

**Pull request merged**
